### PR TITLE
requirements.txt added for easy dependency install

### PR DESCRIPTION
**Pull request by morph8hprom**
Added requirements.txt including the latest version for required non-standard libraries and modified README.md to include instructions for the installation process.

### CODE REVIEW

**Comment by morph8hprom** [comment]
Please make sure to add the hacktober-accepted label if you intend to accept my pull request so that I can receive credit.

**Comment by Hyperion101010** [comment]
I just merged one PR can you update the branch and then push the changes. I will also remove excel files today.

**Comment by morph8hprom** [comment]
Ah I see.  It was fine before the other pull request was merged.  I'll have to fix it when I get out of work today.  Thank you.

**Comment by morph8hprom** [comment]
Also it appears to require a label that says 'hacktoberfest-accepted' as this is still showing as a pull request in an ineligible repo.

**Comment by morph8hprom** [comment]
@Hyperion101010 this PR is ready to merge whenever you'd like.  It still needs the hacktoberfest-accepted label as I mentioned though, as apparently just "hacktoberfest" doesn't count towards the contest.

**Comment by morph8hprom** [comment]
@Hyperion101010  I'm going to assume that this won't get merged.  It was a bit irresponsible to add the hacktoberfest tag to anything in your project if you didn't intend to actually commit to it.

**Comment by Hyperion101010** [comment]
Apologies, I have merged it. 
Please keep contributing.

**Pull request merged**
